export const PROVIDERS = [
    {
        id: 'openai',
        name: 'OpenAI',
        description: 'Industry standard for high-quality generation and reasoning.',
        docsUrl: 'https://platform.openai.com/api-keys',
        placeholder: 'sk-...',
    },
    {
        id: 'anthropic',
        name: 'Anthropic',
        description: 'Claude models, excellent for creative writing and nuanced prompts.',
        docsUrl: 'https://console.anthropic.com/settings/keys',
        placeholder: 'sk-ant-...',
    },
    {
        id: 'google',
        name: 'Google Gemini',
        description: 'Fast and capable models with large context windows.',
        docsUrl: 'https://aistudio.google.com/app/apikey',
        placeholder: 'AIza...',
    },
    {
        id: 'groq',
        name: 'Groq',
        description: 'Extremely fast inference, great for real-time interactions.',
        docsUrl: 'https://console.groq.com/keys',
        placeholder: 'gsk_...',
    },
    {
        id: 'openrouter',
        name: 'OpenRouter',
        description: 'Aggregator providing access to many models (Llama 3, Mistral, etc).',
        docsUrl: 'https://openrouter.ai/keys',
        placeholder: 'sk-or-...',
    },
    {
        id: 'cohere',
        name: 'Cohere',
        description: 'Specialized enterprise-grade models for specific tasks.',
        docsUrl: 'https://dashboard.cohere.com/api-keys',
        placeholder: 'Bear...',
    },
    {
        id: 'together',
        name: 'Together AI',
        description: 'Cloud platform for open-source models like Llama and Mixtral.',
        docsUrl: 'https://api.together.xyz/settings/api-keys',
        placeholder: '...',
    },
    {
        id: 'mistral',
        name: 'Mistral AI',
        description: 'European AI lab with efficient and powerful open-weights models.',
        docsUrl: 'https://console.mistral.ai/api-keys',
        placeholder: '...',
    },
    {
        id: 'perplexity',
        name: 'Perplexity',
        description: 'Access to online models with search capabilities.',
        docsUrl: 'https://www.perplexity.ai/settings/api',
        placeholder: 'pplx-...',
    },
    {
        id: 'deepinfra',
        name: 'DeepInfra',
        description: 'Blazing fast inference for open-source models at low cost.',
        docsUrl: 'https://deepinfra.com/dash/api_keys',
        placeholder: '...',
    },
    {
        id: 'huggingface',
        name: '🤗 HuggingFace',
        description: 'Optional. Increases rate limit from 1,000 to 100,000 requests/day. Get token at huggingface.co/settings/tokens',
        docsUrl: 'https://huggingface.co/settings/tokens',
        placeholder: 'hf_...',
    },
];
